#!/opt/homebrew/bin/bash
#
# gh-dl-release! It works!
#
# This script downloads an asset from latest or specific Github release of a
# private repo. Feel free to extract more of the variables into command line
# parameters.
#
# PREREQUISITES
#
# curl, wget, jq
#
# USAGE
#
# Set all the variables inside the script, make sure you chmod +x it, then
# to download specific version to my_app.tar.gz:
#
#     gh-dl-release 2.1.1 my_app.tar.gz
#
# to download latest version:
#
#     gh-dl-release latest latest.tar.gz
#
# If your version/tag doesn't match, the script will exit with error.

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

TOKEN=$GHACCESSTOKEN
REPO="tallamjr/curriculum-vitae"
FILENAME="tarekallam-cv.pdf"    # the name of your release asset file, e.g. build.tar.gz
VERSION="latest"                # tag name or the word "latest"
GITHUB="https://api.github.com"

# assets list you want to download
AseertsList=(
 $FILENAME
)

function gh_curl() {
  curl -H "Authorization: token $TOKEN" \
       -H "Accept: application/vnd.github.v3+json" \
       $@
}

assets=$(gh_curl -s $GITHUB/repos/$REPO/releases/tags/$VERSION)

for row in $(echo "${assets}" | jq -c '.assets[]'); do
name=$( jq -r  '.name' <<< "${row}" )
echo ${name}
    if [[ ${AseertsList[*]} =~ ${name} ]] ; then

        id=$( jq -r  '.id' <<< "${row}" )

        wget -q --auth-no-challenge --header='Accept:application/octet-stream' \
        https://$TOKEN:@api.github.com/repos/$REPO/releases/assets/$id \
        -O $ROOT/src/assets/${name}
    fi
done
