name: ci.deployment
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml
        miniforge-version: latest
    - name: Configure Git Credentials
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
    - uses: actions/cache@v4
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: |
          mkdocs-material-
    - run: |
        sudo apt install pandoc
        conda init bash
        source /home/runner/miniconda3/etc/profile.d/conda.sh
        conda env create -f environment.yml
        conda activate web
    - run: pip install -r requirements.txt
    - run: mkdocs gh-deploy --force
