name: ci.deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Deploy documentation
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          sudo apt-get update
          sudo apt-get install pandoc=2.19.2
          sudo apt-get install pandoc-citeproc
          pip install -U pip
          pip install -r requirements.txt
          pip install mkdocs-material
          mkdocs gh-deploy --force
