name: ci.deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: web
          environment-file: environment.yml
          python-version: 3.x
          auto-activate-base: false

      - shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Deploy documentation
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          conda env update --file ${{ github.workspace }}/environment.yml
          PATH="/usr/share/miniconda/envs/web/bin:$PATH"
          pip install -U pip
          pip install -r requirements.txt
          pip install mkdocs-material
          mkdocs gh-deploy --force
